name: Support Query Workflow
on:
  push:
    branches:
      - 'master'
      - 'feat**'      

jobs:
  build-code:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Test running a powershell script
        shell: powershell
        run: |
          .\Test-Script.ps1